# Generated by Django 4.2.4 on 2023-09-04 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invista_me', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investimento',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 9, 4, 18, 22, 43, 65964)),
        ),
    ]
